// Build ID helpers — the single source of truth for the Playground build
// identifier format. See docs/development.md ("The Build ID").
//
// Canonical format: YYYYMMDDTHHMMSSZ-<sha8>[-dirty]
// Example:          20260816T065012Z-9e39f37d
//
// The timestamp is the BUILD time (UTC), not the commit time, so a periodic
// rebuild of an unchanged commit still produces a new, distinct Build ID.
// This is deliberately not a semantic version: these projects ship a rolling
// release and the identifier names one deployed artifact.

export const SHORT_SHA_LENGTH = 8;

/** SHA placeholder used when the build runs outside a git checkout. */
export const UNKNOWN_SHA = "nogit";

const TIMESTAMP_PATTERN = String.raw`\d{8}T\d{6}Z`;
const SHA_PATTERN = `[0-9a-f]{${SHORT_SHA_LENGTH}}|${UNKNOWN_SHA}`;

export const BUILD_VERSION_PATTERN = new RegExp(
  `^(${TIMESTAMP_PATTERN})-(${SHA_PATTERN})(-dirty)?$`,
);

/** Format a Date as the UTC `YYYYMMDDTHHMMSSZ` timestamp component. */
export function formatBuildTimestamp(date) {
  const pad = (value, width = 2) => String(value).padStart(width, "0");
  return (
    `${pad(date.getUTCFullYear(), 4)}${pad(date.getUTCMonth() + 1)}` +
    `${pad(date.getUTCDate())}T${pad(date.getUTCHours())}` +
    `${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}Z`
  );
}

/** Reduce any git revision to the canonical short SHA. */
export function normalizeGitSha(value) {
  const sha = String(value || "")
    .trim()
    .toLowerCase();
  if (!/^[0-9a-f]{7,40}$/.test(sha)) {
    return UNKNOWN_SHA;
  }
  return sha.slice(0, SHORT_SHA_LENGTH);
}

/** Build the canonical identifier from its parts. */
export function composeBuildVersion({ timestamp, gitSha, dirty = false }) {
  return `${timestamp}-${gitSha}${dirty ? "-dirty" : ""}`;
}

/** Split a canonical identifier back into its parts, or null when malformed. */
export function parseBuildVersion(value) {
  const match = BUILD_VERSION_PATTERN.exec(String(value || ""));
  if (!match) {
    return null;
  }
  return { timestamp: match[1], gitSha: match[2], dirty: Boolean(match[3]) };
}

export function isValidBuildVersion(value) {
  return parseBuildVersion(value) !== null;
}

/**
 * Resolve the full build metadata.
 *
 * `env.BUILD_VERSION` wins outright so one CI pipeline can generate the Build
 * ID once and replay the exact same value through every job. `env.BUILD_SHA`
 * overrides only the revision, which CI uses to record a pull request's head
 * commit instead of the ephemeral merge commit `actions/checkout` produces.
 *
 * `git` is injected so this stays a pure function under test.
 */
export function resolveBuildMetadata({ env = {}, now = new Date(), git } = {}) {
  const generatedAt = now.toISOString();
  const override = String(env.BUILD_VERSION || "").trim();

  if (override) {
    const parsed = parseBuildVersion(override);
    return {
      buildVersion: override,
      generatedAt,
      gitSha: parsed ? parsed.gitSha : normalizeGitSha(git?.sha?.()),
      dirty: parsed ? parsed.dirty : Boolean(git?.dirty?.()),
    };
  }

  const gitSha = normalizeGitSha(env.BUILD_SHA || git?.sha?.());
  const dirty = Boolean(git?.dirty?.());
  return {
    buildVersion: composeBuildVersion({
      timestamp: formatBuildTimestamp(now),
      gitSha,
      dirty,
    }),
    generatedAt,
    gitSha,
    dirty,
  };
}

/** Render the generated ES module consumed by the app, worker and tests. */
export function renderBuildVersionModule(metadata) {
  return [
    "// Generated by scripts/write-build-version.mjs — do not edit.",
    `export const BUILD_VERSION = ${JSON.stringify(metadata.buildVersion)};`,
    "export const BUILD_METADATA = {",
    `  buildVersion: ${JSON.stringify(metadata.buildVersion)},`,
    `  generatedAt: ${JSON.stringify(metadata.generatedAt)},`,
    `  gitSha: ${JSON.stringify(metadata.gitSha)},`,
    `  dirty: ${JSON.stringify(metadata.dirty)},`,
    "};",
    "",
  ].join("\n");
}
